steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sara-myapps-repository/sara-myapp:$SHORT_SHA'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sara-myapps-repository/sara-myapp:$SHORT_SHA'



 # 216  PROJECT_ID="sara-project-401601"
 # 217  gcloud artifacts repositories list --limit=5
 # 218  APP_ARTIFACT_REPO="sara-myapps-repository"
