apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: myapp1-deployment
spec: # Dictionary
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:  
    metadata: # Dictionary
      name: myapp1-pod
      labels: # Dictionary
        app: myapp1  # Key value pairs
    spec:
      containers: # List
        - name: myapp1-container
          #image: us-central1-docker.pkg.dev/kdaida123/myapps-repository/myapp1:d1c3b88
          #image: us-central1-docker.pkg.dev/sara-project-401601/sara-myapps-repository/sara-myapp:30e9601
          image: us-central1-docker.pkg.dev/sara-project-401601/sara-myapps-repository/sara-myapp:23322a7
          ports: 
            - containerPort: 80  
    
